%% Load .mat file
data = load('cortex.mat');  % replace with your filename
Vertices = data.Vertices;     % Nx3 array
Faces = data.Faces;           % Mx3 array
raw = data.raw;               % vertex-wise data

%% Define cortex (motor) voxel numbers based on your AAL table
motor_labels = {'Precentral', 'Supp_Motor_Area', 'Rolandic_Oper'};
AAL2_label = {"Precentral", "Precentral", "Frontal_Sup", "Frontal_Sup", "Frontal_Mid", "Frontal_Mid",...
        "Frontal_Inf_Oper", "Frontal_Inf_Oper", "Frontal_Inf_Tri", "Frontal_Inf_Tri", "Frontal_Inf_Orb", ...
        "Frontal_Inf_Orb", "Rolandic_Oper", "Rolandic_Oper", "Supp_Motor_Area", "Supp_Motor_Area", ...
        "Olfactory", "Olfactory", "Frontal_Sup_Med", "Frontal_Sup_Med", "Frontal_Med_Orb", ...
        "Frontal_Med_Orb", "Rectus", "Rectus", "OFCmed", "OFCmed", "OFCant", "OFCant", "OFCpost", ...
        "OFCpost", "OFClat", "OFClat", "Insula", "Insula", "Cingulate_Ant", "Cingulate_Ant", "Cingulate_Mid",... 
        "Cingulate_Mid", "Cingulate_Post", "Cingulate_Post", "Hippocampus", "Hippocampus", ...
        "ParaHippocampal", "ParaHippocampal", "Amygdala", "Amygdala", "Calcarine", "Calcarine", "Cuneus", ...
        "Cuneus", "Lingual", "Lingual", "Occipital_Sup", "Occipital_Sup", "Occipital_Mid", "Occipital_Mid", ...
        "Occipital_Inf", "Occipital_Inf", "Fusiform", "Fusiform", "Postcentral", "Postcentral", ...
        "Parietal_Sup", "Parietal_Sup", "Parietal_Inf", "Parietal_Inf", "SupraMarginal", "SupraMarginal",... 
        "Angular", "Angular", "Precuneus", "Precuneus", "Paracentral_Lobule", "Paracentral lobule", ...
        "Caudate", "Caudate", "Putamen", "Putamen", "Pallidum", "Pallidum", ...
        "Thalamus", "Thalamus", "Heschl", "Heschl", ...
        "Temporal_Sup", "Temporal_Sup", "Temporal_Pole_Sup", "Temporal_Pole_Sup", ...
        "Temporal_Mid", "Temporal_Mid", "Temporal_Pole_Mid", "Temporal_Pole_Mid",...
        "Temporal_Inf", "Temporal_Inf", "Cerebellum_Crus1", "Cerebellum_Crus1", ...
        "Cerebellum_Crus2", "Cerebellum_Crus2", "Cerebellum_3", "Cerebellum_3", ...
        "Cerebellum_4_5", "Cerebellum_4_5", "Cerebellum_6", "Cerebellum_6", ...
        "Cerebellum_7b", "Cerebellum_7b", "Cerebellum_8", "Cerebellum_8", ...
        "Cerebellum_9", "Cerebellum_9", "Cerebellum_10", "Cerebellum_10", ...
        "Vermis_1_2", "Vermis_3", "Vermis_4_5",  "Vermis_6", "Vermis_7", "Vermis_8", "Vermis_9", "Vermis_10"
    % Continue for all 120
};
voxel_no = 1:120;

motor_idx = ismember(AAL2_label, motor_labels);
motor_voxels = voxel_no(motor_idx);

%% Create a scalar array for VTK
vtk_scalars = zeros(size(Vertices,1),1);   % initialize zeros for all vertices
vtk_scalars(motor_voxels) = raw(motor_voxels);  % assign raw values to motor cortex vertices

%% Write VTK file (ASCII format)
vtk_filename = 'motor_cortex.vtk';
fid = fopen(vtk_filename,'w');

fprintf(fid, '# vtk DataFile Version 3.0\n');
fprintf(fid, 'Motor cortex scalar data\n');
fprintf(fid, 'ASCII\n');
fprintf(fid, 'DATASET POLYDATA\n');

% Write points
fprintf(fid, 'POINTS %d float\n', size(Vertices,1));
fprintf(fid, '%f %f %f\n', Vertices');  % note transpose for fprintf

% Write faces
fprintf(fid, 'POLYGONS %d %d\n', size(Faces,1), size(Faces,1)*4);
fprintf(fid, '3 %d %d %d\n', (Faces-1)');  % VTK uses 0-based indexing

% Write vertex scalars
fprintf(fid, 'POINT_DATA %d\n', size(Vertices,1));
fprintf(fid, 'SCALARS motor_data float 1\n');
fprintf(fid, 'LOOKUP_TABLE default\n');
fprintf(fid, '%f\n', vtk_scalars);

fclose(fid);

disp(['Saved motor cortex data to ', vtk_filename]);
